function Hd = aa_filter
%AA_FILTER Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 9.3 and Signal Processing Toolbox 7.5.
% Generated on: 31-Oct-2018 20:59:27

% Chebyshev Type I Lowpass filter designed using FDESIGN.LOWPASS.

% All frequency values are in MHz.
Fs = 2048000;  % Sampling Frequency

Fpass = 127000;      % Passband Frequency
Fstop = 128000;      % Stopband Frequency
Apass = 0.05;        % Passband Ripple (dB)
Astop = 50;          % Stopband Attenuation (dB)
match = 'passband';  % Band to match exactly

% Construct an FDESIGN object and call its CHEBY1 method.
h  = fdesign.lowpass(Fpass, Fstop, Apass, Astop, Fs);
Hd = design(h, 'cheby1', 'MatchExactly', match);

% [EOF]
