function Hd = differentiator_filter
%DIFFERENTIATOR_FILTER Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 9.4 and DSP System Toolbox 9.6.
% Generated on: 16-Oct-2018 08:46:08

% Equiripple Differentiator filter designed using the FIRPM function.

% All frequency values are normalized to 1.
M = 32;
beta = 2.4;
w = kaiser(M, beta);
n = -((M-1)/2):1:((M-1)/2);
h_diff = (cos(pi * (n)) ./ (n)) - (sin(pi * (n)) ./ (pi * (n).^2));
b = w.*transpose(h_diff);
fvtool(b, 1);
firtype(b)
% Hd = dfilt.dffir(b);
% [gd, ] = grpdelay(Hd);
% firtype(Hd)
% fvtool(Hd)
% [EOF]
