function Hd = elliptic
%ELLIPTIC Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 9.4 and Signal Processing Toolbox 8.0.
% Generated on: 12-Oct-2018 17:04:35

% Elliptic Lowpass filter designed using FDESIGN.LOWPASS.

% All frequency values are normalized to 1.

Fpass = 0.053571428571;  % Passband Frequency
Fstop = 0.089285714286;  % Stopband Frequency
Apass = 1;               % Passband Ripple (dB)
Astop = 50;              % Stopband Attenuation (dB)
match = 'both';          % Band to match exactly

% Construct an FDESIGN object and call its ELLIP method.
h  = fdesign.lowpass(Fpass, Fstop, Apass, Astop);
Hd = design(h, 'ellip', 'MatchExactly', match);
disp('Order: ')
disp(filtord(Hd.sosMatrix));
fvtool(Hd)
% [EOF]
